### ISSUE TITLE
Compound word だしといて is split into だ + しといて

### ISSUE THREAD

**Issue by dddlr** [tshatrov/ichiran#12]
Hi again!

I recently came across a tweet with the following text:

もーすぐ　できるよン　お皿だしといてー
https://twitter.com/ktandoku/status/1350350938347696130 (fully SFW)

Looks like on ichi.moe, [だしといて](https://ichi.moe/cl/qr/?q=%E3%81%A0%E3%81%97%E3%81%A8%E3%81%84%E3%81%A6&r=htr) (and the uncontracted だしておいて too) is incorrectly segmented as だ + しといて instead of a compound word だしといて.

On the other hand, using the kanji form of だす ([出しといて](https://ichi.moe/cl/qr/?q=%E5%87%BA%E3%81%97%E3%81%A8%E3%81%84%E3%81%A6&r=htr) and 出しておいて) work fine.

**Comment by dddlr** [comment]
Also - I'm not sure if I should bring this up in a separate issue, but as a Japanese learner I feel that the current breakdown for "[verb] + とく" compound verbs might be a bit confusing?

Currently for 出しといて, this is displayed:
> 出しといて 【だしといて】
> Compound word: 出して + といて
> 出して 【だして】
> [v5s] Conjunctive (~te)
> 出す 【だす】
> [...]
> といて
> [to do in advance / to leave in the current state expecting a later change]
> [v5k] Conjunctive (~te)
> とく

There's nothing indicating that とく here is a contraction of ておく (JMDict on the other hand mentions this), and the breakdown into "出して + といて" seems a bit misleading in my opinion.

I think ideally it should be treated as if it were the uncontracted 出しておいて (i.e. the breakdown should be 出して + おいて), but I understand if there's technical limitations involved here.

**Comment by tshatrov** [comment]
I'll push a fix for だし+suffixes being split incorrectly soon (basically I'll forbid any form of する right after だ)

As for compound word breakdown, you're correct that it's not really consistent right now (for example しちゃ is shown as して＋は), but it's a bit more annoying to do this for conjugated suffixes. Also since JMdict does have the word とく for て+おく, it's also in ichiran database and it's listed in [WordInfo for といて](https://ichi.moe/cl/word/?q=%E3%81%A8%E3%81%84%E3%81%A6), albeit at the bottom because this word is forbidden to be used by itself and its score is 0.

**Comment by tshatrov** [comment]
So the original issue [is now fixed](https://ichi.moe/cl/qr/?q=%E3%81%A0%E3%81%97%E3%81%A8%E3%81%84%E3%81%A6&r=htr) . I wanted to change the compound word text of this suffix as well, but there is a technical issue preventing this currently, as some forms of suffix とく are disabled and this wouldn't be possible if it was parsed as おく.

**Comment by dddlr** [comment]
Thanks for fixing the issue! :)
