### ISSUE TITLE
Curious treatment of kanji-break list

### ISSUE THREAD

**Issue by vpltd-kgalaj** [tshatrov/ichiran#46]
Looking at the code, it seems that kanji-break list is assummed to have different content constraints in different places.

Specifically, first in join-substring-words*, for every start-end range for which at least one word is found, kanji breaks within that range are found and added to the kanji-breaks list. There is a single list for all the ranges, so if the same two kanjis are parts of more than one word (found with different ranges), the position of the break will be added to the list more than once.

Then, just before gen-score call, we have a:
>        for kb = (mapcar (lambda (n) (- n start)) (intersection (list start end) kanji-break))
which will put duplicates in the kb list, if it finds them in kanji-break list. So far, it looks like you are counting places that break more than one found word range as many times as there are different word ranges found. This code also reindexes the breaks so that they start from the beginning of the word that's about to be scored. So the resultting kb list could have, for example, contents like nil, (0), (1), (2), (0 1), (0 2) (typical) , but it could also have (0 0), (1 1), (0 0 1 1) (albeit rarely, most likely).

But then, when the kanji-break list contents are actually used, at the very beginning of kanji-break-penalty, we have:
>  (let ((end (cond ((cdr kanji-break) :both)
                   ((eql (car kanji-break) 0) :beg)
                   (t :end)))

which seems to squarely assume, that the kanji-break (taken from kb) list will have either (0), (word-size), or (0 word-size) content. It can't be nil, of kanji-break-penallty wouldn't ever be called.

So there can be words, beginning of which breaks nothing, but the end of which comes to break more than one (start end) range, for which there was a word found, and so for which the kb will contain the word-size more then once, for example, for a 1-character/mora word it'll be (1 1), and then this 'let' will pick the end variable to the :both , even though it should have picked :end.

Is this by design? I seem to be missing something here, as I'd assume that if it's a bug, it'll have wide-ranging effects on segmentation.

**Comment by tshatrov** [comment]
Hi, thanks for the report. TBH I wrote this all a long time ago, but let me try to remember what this does.

First of all, the term "kanji break" is used for segments which break up 2 sequential kanji which are already a part of some other segment, which is considered "bad" for scoring (even though there are legitimate cases for such a segmentation). For example "改題します" which is a valid segment can be split as "改"+"題します" which would be an example of a segmentation penalized for kanji break.

First it finds the possible positions where a kanji break may occur. It seems that you're correct and the same position can be added more than once. For example for above string `join-substring-words*` will return `(1 1 1)` as kanji-break.

Next we take the list of beginning and end of a segment and intersect it with kanji-break list, and then the starting position is subtracted so I assume the result is either `nil`, `(0)`, `(len)` or `(0 len)`  or `(len 0)` where `len` is the length of the word. However you're correct that according to [the spec](http://clhs.lisp.se/Body/f_isec_.htm) `intersection` is allowed to return duplicate elements depending on implementation.

In practice, when using SBCL and the first element is a distinct pair, there are no duplicates in the return value. So the bug is avoided. But if the arguments were in a different order, it would return duplicates.

```
ICHIRAN/DICT> (intersection (list 1 4) (list 1 1 4 4 4 1 1 4 4))
(4 1)
ICHIRAN/DICT> (intersection (list 1 1 4 4 4 1 1 4 4) (list 1 4))
(4 4 1 1 4 4 4 1 1)
```

I'm going to fix this to be compliant to the spec, but I believe this issue does not result in a bug in the current implementation.

**Comment by vpltd-kgalaj** [comment]
Thank you for the information, and confirmation that it's supposed to not contain duplicated indexes. I thought that in theory a kanji break that breaks more entries might be a more serious one, but then you'd probably be counting all words, not distinct ranges.
